# Generated by Django 2.0 on 2017-12-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RagarajaInstructions',
            new_name='RagarajaInstruction',
        ),
    ]
