# Generated by Django 2.0 on 2017-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171218_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
